# Generated by Django 5.2.6 on 2025-09-05 20:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria de Alimento',
                'verbose_name_plural': 'Categorias de Alimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('energia_kcal', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Energia (kcal)')),
                ('proteina_g', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proteína (g)')),
                ('lipidios_g', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lipídios (g)')),
                ('carboidrato_g', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carboidrato (g)')),
                ('fibra_alimentar_g', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fibra Alimentar (g)')),
                ('calcio_mg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cálcio (mg)')),
                ('ferro_mg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ferro (mg)')),
                ('sodio_mg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sódio (mg)')),
                ('vitamina_c_mg', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vitamina C (mg)')),
                ('medida_caseira', models.CharField(help_text='Ex: 1 colher de sopa, 1 unidade', max_length=100)),
                ('quantidade_medida_caseira', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade da medida caseira (g)')),
                ('ativo', models.BooleanField(default=True)),
                ('fonte', models.CharField(default='TBCA - USP', max_length=200, verbose_name='Fonte dos dados')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alimentos.categoriaalimento')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nome'],
            },
        ),
    ]
