# Generated by Django 5.2.6 on 2026-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='restricao',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma'), ('DIABETES', 'Diabético'), ('HIPERTENSAO', 'Hipertenso'), ('AMBOS', 'Diabético e Hipertenso')], default='', max_length=20, verbose_name='Restrição de saúde'),
        ),
    ]
