# Generated by Django 5.2.6 on 2025-09-10 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome padronizado do exame, ex: 'Glicemia de Jejum'", max_length=100, unique=True)),
                ('unidade_padrao', models.CharField(help_text="Unidade de medida padrão, ex: 'mg/dL'", max_length=20)),
                ('ref_min', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de referência mínimo', max_digits=10, null=True)),
                ('ref_max', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de referência máximo', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído'), ('A', 'Analisado')], default='P', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_exames', to='plataforma.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_diagnostico_ia', models.TextField(blank=True, editable=False, null=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='exames.solicitacaoexame')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exames.tipoexame')),
            ],
            options={
                'unique_together': {('solicitacao', 'tipo_exame')},
            },
        ),
    ]
