# Generated by Django 5.2.6 on 2025-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_alter_resultadoexame_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoexame',
            name='unidade_padrao',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
