# Generated by Django 5.2.6 on 2026-06-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_vendas', '0002_assinatura_eh_teste_gratis_alter_assinatura_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Usado na URL de checkout, ex: 1-mes', unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do plano e/ou condições da promoção')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracao_dias', models.PositiveIntegerField(default=30, help_text='Duração da assinatura em dias')),
                ('ativo', models.BooleanField(default=True, help_text='Exibir este plano na página de vendas')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro)')),
                ('eh_teste_gratis', models.BooleanField(default=False, help_text='Marca este como o plano de teste grátis')),
                ('eh_promocional', models.BooleanField(default=False, help_text='Marca este plano como promocional')),
                ('validade_promocao', models.DateTimeField(blank=True, help_text='Data/hora limite da promoção. Após essa data o plano não aparece mais (se promocional).', null=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem', 'preco'],
            },
        ),
        migrations.AddField(
            model_name='assinatura',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('teste', 'Teste Gratuito'), ('pendente', 'Pendente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='validade',
            field=models.DateTimeField(),
        ),
    ]
