# Generated by Django 5.2.6 on 2025-09-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], max_length=24)),
                ('estadocivil', models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viuvo(a)', 'Viuvo(a)')], max_length=25)),
                ('datanascimento', models.DateField(blank=True, null=True)),
                ('naturalidade', models.CharField(max_length=120)),
                ('profissao', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=50, null=True)),
                ('nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DadosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('percentual_gordura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('percentual_musculo', models.DecimalField(decimal_places=1, max_digits=4)),
                ('colesterol_hdl', models.IntegerField()),
                ('colesterol_ldl', models.IntegerField()),
                ('colesterol_total', models.IntegerField()),
                ('trigliceridios', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAFE_MANHA', 'Café da Manhã'), ('LANCHE_MANHA', 'Lanche da Manhã'), ('ALMOCO', 'Almoço'), ('LANCHE_TARDE', 'Lanche da Tarde'), ('JANTAR', 'Jantar'), ('CEIA', 'Ceia')], default='ALMOCO', max_length=20)),
                ('titulo', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Plano Alimentar', max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('objetivo', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
                ('refeicoes', models.ManyToManyField(to='plataforma.refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_g', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('observacoes', models.TextField(blank=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='plataforma.refeicao')),
            ],
            options={
                'verbose_name': 'Item de Refeição',
                'verbose_name_plural': 'Itens de Refeição',
            },
        ),
    ]
