# Generated by Django 5.2.6 on 2025-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospaciente',
            name='colesterol_hdl',
        ),
        migrations.RemoveField(
            model_name='dadospaciente',
            name='colesterol_ldl',
        ),
        migrations.RemoveField(
            model_name='dadospaciente',
            name='colesterol_total',
        ),
        migrations.RemoveField(
            model_name='dadospaciente',
            name='trigliceridios',
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_gordura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_musculo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
