# Generated by Django 5.2.6 on 2025-10-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_remove_dadospaciente_colesterol_hdl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='É WhatsApp?'),
        ),
    ]
