# Generated by Django 5.2.6 on 2026-08-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_alimento_restricao'),
        ('plataforma', '0003_pacientes_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='restricao_diabetico',
            field=models.BooleanField(default=False, verbose_name='Diabético'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='restricao_hipertenso',
            field=models.BooleanField(default=False, verbose_name='Hipertenso'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='restricao_outros',
            field=models.CharField(blank=True, max_length=200, verbose_name='Outras restrições'),
        ),
        migrations.CreateModel(
            name='SubstituicaoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_g', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade (g)')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alimento_substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento', verbose_name='Alimento substituto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='plataforma.itemrefeicao')),
            ],
            options={
                'verbose_name': 'Substituição de Refeição',
                'verbose_name_plural': 'Substituições de Refeições',
            },
        ),
    ]
