# Generated by Django 5.1.7 on 2025-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_opcao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='Opcao'),
        ),
    ]
