# Generated by Django 5.2.6 on 2025-10-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofissional',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_profissionais/'),
        ),
    ]
