# Generated by Django 5.2.6 on 2026-06-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_perfilprofissional_logotipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='pode_excluir_evolucoes',
            field=models.BooleanField(default=False, verbose_name='Pode excluir evoluções'),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ativacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AlteracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novo_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alteracao_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
