# Generated by Django 5.1.7 on 2025-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_perfilprofissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofissional',
            name='cfn',
            field=models.CharField(max_length=22),
        ),
    ]
