# Generated by Django 5.2.6 on 2026-08-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_perfilprofissional_pode_excluir_evolucoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
