# Generated by Django 5.1.7 on 2025-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_alter_perfilprofissional_cfn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='nomeclinica',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
